# 验证器插件系统配置
# Validator Plugin System Configuration

# 启用的插件列表
enabled_plugins: []           # 暂不启用任何扩展插件

# 插件权重配置（影响最终评分）
plugin_weights: {}

# 自定义插件目录
custom_plugins_dir: "plugins/"

# 插件特定设置
plugin_settings: {}           # 暂无插件特定设置

# 评分融合策略
scoring_strategy:
  mode: "weighted_average"               # 加权平均模式
  fallback_score: 5.0                   # 插件失败时的默认分数
  normalize_scores: true                 # 标准化分数到0-10范围

# 扩展评分维度（覆盖原有维度）
dimension_overrides:
  # 禁用maintainability维度覆盖，让质量评估插件系统处理
  maintainability:
    enabled: false
    plugins: []                         # 暂无插件
    weights: []                         # 对应权重
  
  # 添加新的评分维度
  # reliability:
  #   enabled: false
  #   plugins: ["test_coverage", "performance"] 
  #   weights: [0.7, 0.3]

# 报告设置
reporting:
  detailed_plugin_results: true         # 显示详细插件结果
  include_recommendations: true         # 包含改进建议
  export_format: "markdown"             # 导出格式
